steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hotelbot-siao-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hotelbot-siao-image']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=deployment.yaml
    - --image=gcr.io/aesthetic-genre-277613/hotelbot-siao-image
    - --location=us-central1-c
    - --cluster=future-disneyland-cluster
